In [1]:
import pandas as pd 
# pandas (as pd) handles the tabular data.
import numpy as np 
# numpy (as np) provides support for mathematical arrays and missing value placeholders.
import matplotlib as plt 
# matplotlib.pyplot (as plt) are used to create charts and graphs.
import seaborn as sns 
# seaborn (as sns) are used to create charts and graphs.

In [2]:
%matplotlib inline 
#This is a Jupyter Notebook magic command.
#It ensures that any plots or visualizations generated by matplotlib/seaborn are rendered directly inside the notebook,
#right below the code cell, rather than opening in a separate pop-up window.

plt.rcParams['figure.figsize'] = (10, 5)
# Modifies global configuration settings for Matplotlib.
# It sets the default width and height 
# e.g. all subsequent plots to 10 inches wide by 5 inches tall.

sns.set_style('whitegrid')
# Configures the aesthetic theme for Seaborn plots. 
# The 'whitegrid' style gives charts a clean, white background with subtle gray gridlines, making data points easier to read.

### 1.1

In [3]:
df = pd.read_csv('car_prices.csv')
# Reads the raw dataset from the external CSV file named car_prices.csv 
# Loads it into memory as a pandas DataFrame object 
# Which is saved to the variable df

In [20]:
df.head(5)
# Previews the first 2 rows of your newly loaded DataFrame. 
# It allows you to quickly inspect the column names (like year, make, model, sellingprice) and see what the data actually looks like.

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [10]:
df.shape 
# Why no ()
# df.shape is an Attribute (Property)
# You are just reading a property, not running a function.
# Previews the first 5 rows of your newly loaded DataFrame.
# It allows you to quickly inspect the column names (like year, make, model, sellingprice) and see what the data actually looks like.

(558837, 16)

In [11]:
df.info()
# Why ()
# df.info() is a Method (Action)
# In Python, parenthesis tell the program to execute the function.
# If you run df.info without the brackets, Python won't run the report—it will just tell you that df.info is a built-in method.
# Running df.info() executes a built-in method that scans your DataFrame on the fly and prints out a detailed diagnostic report.
# The Structure: It tells you this is a standard pandas DataFrame.
# Row Count: Your dataset has 558,837 rows (indexed from 0 to 558,836).
# Column Count: There are 16 columns in total.

<class 'pandas.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  str
 2   model         548438 non-null  str
 3   trim          548186 non-null  str
 4   body          545642 non-null  str
 5   transmission  493485 non-null  str
 6   vin           558833 non-null  str
 7   state         558837 non-null  str
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  str
 11  interior      558088 non-null  str
 12  seller        558837 non-null  str
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  str
dtypes: float64(4), int64(1), str(11)
memory usage: 68.2 MB

In [13]:
df.describe()
# By default, this method automatically filters for columns with numeric data types (int64 and float64) 
# Computes key statistical metrics for each. 
# It helps you quickly spot the distribution of your data, central tendencies, and potential anomalies or outliers.

,year,condition,odometer,mmr,sellingprice
count,558837.000000,547017.000000,558743.000000,558799.000000,558825.000000
mean,2010.038927,30.672365,68320.017767,13769.377495,13611.358810
std,3.966864,13.402832,53398.542821,9679.967174,9749.501628
min,1982.000000,1.000000,1.000000,25.000000,1.000000
25%,2007.000000,23.000000,28371.000000,7100.000000,6900.000000
50%,2012.000000,35.000000,52254.000000,12250.000000,12100.000000
75%,2013.000000,42.000000,99109.000000,18300.000000,18200.000000
max,2015.000000,49.000000,999999.000000,182000.000000,230000.000000

In [17]:
print(f"Number of records: {len(df)}")
# len(df): This calculates the total number of rows (records) currently in your DataFrame.

print("\nData types:")
# df.dtypes: This property lists every column name alongside its assigned data type (e.g., int64 for integers, float64 for decimals, and str/object for text)

df.dtypes 
# Is an attribute
# Returns the data type (dtype) of each column in your DataFrame.

Number of records: 558837

Data types:

year              int64
make                str
model               str
trim                str
body                str
transmission        str
vin                 str
state               str
condition       float64
odometer        float64
color               str
interior            str
seller              str
mmr             float64
sellingprice    float64
saledate            str
dtype: object

### 1.2

In [25]:
df.shape
# Tell me how big this spreadsheet is.
# Gives you two numbers back: (rows, columns).
# Because it's a property/characteristic of the data (and not an action or calculation), you don't put parentheses () at the end of it.

print(f"Shape (rows, columns): {df.shape}")
# Confirm shape (rows and columns) again for clarity

Shape (rows, columns): (558837, 16)

In [28]:
df.columns
# Show me the labels at the top of every column.
# This simply spits out a list of the headers for your 16 columns so you know exactly what variables you have to play with.

print(f"Columns: {df.columns}")

Columns: Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='str')