In [1]:
import pandas as pd # Data manipulation library
import numpy as np # Numerical computing library
import seaborn as sns # Statistical data visualization library
import matplotlib.pyplot as plt  # Core plotting library

%matplotlib inline

In [2]:
df_salesdata = pd.read_csv(r"C:\Users\Shiva Thakur\OneDrive\Desktop\Github\Projects\Python\Datasets\Retail Sales Dataset\sales_data_dictionary.csv")
df_transactions = pd.read_csv(r"C:\Users\Shiva Thakur\OneDrive\Desktop\Github\Projects\Python\Datasets\Retail Sales Dataset\Sales_transactions_2022_2025.csv")

In [ ]:
df_salesdata.head(5)

,Column_Name,Description,Data_Type,Example_Value,Business_Meaning
0,Transaction_ID,Unique identifier for an individual transactio...,Text,T20001234,Transaction-level key
1,Order_ID,Identifier for the customer order; multiple li...,Text,O1001234,Groups order lines into orders
2,Customer_ID,Identifier for the customer,Text,C01234,Supports repeat-customer analysis
3,Customer_Name,Customer name from CRM,Text,Emma Carter,Customer display/identification
4,Customer_Age,Customer age at transaction,Integer,42,Demographic analysis; rare anomalies included

In [4]:
df_transactions.head(5)

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022

In [5]:
df_transactions.isnull().sum()

Transaction_ID              0
Order_ID                    0
Customer_ID                 0
Customer_Name             108
Customer_Age              218
Customer_Gender           162
Customer_Segment            0
Order_Date                  0
Order_Time                  0
Sales_Channel               0
Store_ID                    0
Store_Name                  0
Country                     0
Region                      0
City                        0
Product_ID                  0
Product_Name              144
Product_Category            0
Product_Subcategory         0
Quantity                    0
Unit_Price                  0
Discount_Percentage         0
Sales_Amount                0
Cost_Amount                 0
Profit                      0
Payment_Method            147
Order_Status                0
Shipping_Method             0
Delivery_Days             162
Return_Flag                 0
Return_Reason           16168
Sales_Representative        0
Promotion_Code           9737
Customer_Rating          3435
Inventory_Level           198
Order_Year                  0
dtype: int64

In [8]:
df_transactions.duplicated().value_counts()

False    18000
True        45
Name: count, dtype: int64